version: '3'
services:
    fwday_app:
        build: .
        container_name: "fwday_app"
        depends_on:
          - fwday_db
        links:
          - fwday_db
        environment:
          - NODE_ENV=development
          - LOG_LEVEL=trace
          - HTTP_PORT=8080
          - SHUTDOWN_TIMEOUT=1000
          - CACHE_DEFAULT_VALUE_LENGTH=12
          - CACHE_MAX_AMOUNT=3
          - CACHE_TTL=30
          - CACHE_COLLECTION_NAME=cache
          - MONGODB_CONNECTION_STRING=mongodb://fwday_db:27017/db-cache
        ports:
            - 8080:8080
    fwday_db:
        image: mongo:latest
        container_name: "fwday_db"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
